FROM rust:1.75

WORKDIR /usr/src/mortgagekit-rs

# Install cargo-watch
RUN cargo install cargo-watch

# Copy manifests
COPY Cargo.toml Cargo.lock ./

# Copy source code
COPY src ./src/
COPY tests ./tests/

# Set environment variables
ENV RUST_LOG=debug
ENV RUST_BACKTRACE=1

# Command to run on container start
CMD ["cargo", "watch", "-x", "run"]
